### ISSUE TITLE
kubesphere/kubectl:v1.17.0 pull image wrong

### ISSUE THREAD

**Issue by a943915349** [kubesphere/kubectl#2]
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "74c2cfe3383df693a27495273cf8793529637e174364e3723c3f05e1dcee67fb" network for pod "kubectl-admin-56d86b7fd8-hvlx9": networkPlugin cni failed to set up pod "kubectl-admin-56d86b7fd8-hvlx9_kubesphere-controls-system" network: open /run/flannel/subnet.env: no such file or directory

**Comment by LinuxSuRen** [comment]
Please use `kubespheredev/kubectl:v1.17.0` instead of `kubesphere/kubectl:v1.17.0`. Because `kubesphere/kubectl:v1.17.0` has not been released yet. I'm pretty sure that you can use it after KubeSphere 3.1.0 released.

/close
